version: "3"

services:
  grenouilleapi_postgres:
    image: grenouilleapi_postgres
    container_name: "grenouilleapi_postgres"
    restart: always
    build:
      context: grenouilleapi_postgres
    volumes:
      - "/home/docker/grenouilleapi_postgres/data:/var/lib/postgresql/data"
    env_file:
      - './grenouilleapi_postgres/conf.env'
    ports:
      - '9998:5432'
    network_mode: host

  grenouilleapiti_postgres:
    image: grenouilleapiti_postgres
    container_name: "grenouilleapiti_postgres"
    restart: always
    build:
      context: grenouilleapi_postgres
    volumes:
      - "/home/docker/grenouilleapiti_postgres/data:/var/lib/postgresql/data"
    env_file:
      - './grenouilleapi_postgres/conf.env'
    ports:
      - '9996:5432'
    network_mode: host
  
  grenouilleapi:
    image: grenouilleapi
    container_name: "grenouilleapi"
    restart: always
    build:
      context: ..
      dockerfile: docker/grenouilleapi/Dockerfile
    volumes:
      - "/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9999:9999"
    entrypoint: python3 /grenouille/backend/app.py
    depends_on:
      - grenouilleapi_postgres
    network_mode: host

# Not used ATM
#  grenouilleapi_bot:
#    image: grenouilleapi
#    container_name: "grenouilleapi_bot"
#    restart: always
#    build:
#      context: ..
#      dockerfile: docker/grenouilleapi/Dockerfile
#    entrypoint: python3 /grenouille/backend/bot_app.py
#    depends_on:
#      - grenouilleapi_postgres
#    network_mode: host

  grenouilleapi_rtmp:
    image: grenouilleapi_rtmp
    container_name: grenouilleapi_rtmp
    restart: always
    build:
      context: ..
      dockerfile: docker/grenouilleapi_rtmp/Dockerfile
    ports:
      - "1935:1935"
      - "9997:9997"
