version: "3"

services:
  grenouilleapi_postgres:
    image: grenouilleapi_postgres
    container_name: "grenouilleapi_postgres"
    build:
      context: grenouilleapi_postgres
    volumes:
      - "/home/docker/grenouilleapi_postgres/data:/var/lib/postgresql/data"
    env_file:
      - './grenouilleapi_postgres/conf.env'
    ports:
      - '9998:5432'
    networks:
      - grenouille_network

  grenouilleapi:
    image: grenouilleapi
    container_name: "grenouilleapi"
    build:
      context: ..
      dockerfile: docker/grenouilleapi/Dockerfile
    ports:
      - "9999:9999"
    entrypoint: python3 /grenouille/backend/app.py
    networks:
      - grenouille_network
    depends_on:
      - grenouilleapi_postgres

  grenouille:
    image: grenouille
    container_name: "grenouille"
    build:
      context: ..
      dockerfile: docker/grenouille/Dockerfile
    ports:
      - "9997:8080"
    entrypoint: nginx -g "daemon off;"
    networks:
      - grenouille_network

networks:
  grenouille_network:
