version: "3"

services:
  grenouilleapi_postgres:
    image: grenouilleapi_postgres
    container_name: "grenouilleapi_postgres"
    build:
      context: grenouilleapi_postgres
    volumes:
      - "/home/docker/grenouilleapi_postgres/data:/var/lib/postgresql/data"
    env_file:
      - './grenouilleapi_postgres/conf.env'
    ports:
      - '9998:5432'

  grenouilleapi:
    image: grenouilleapi
    container_name: "grenouilleapi"
    build:
      context: ..
      dockerfile: docker/grenouilleapi/Dockerfile
    ports:
      - "9999:9999"
    entrypoint: python3 /grenouille/backend/app.py
    depends_on:
      - grenouilleapi_postgres

  grenouilleapi_bot:
    image: grenouilleapi_bot
    container_name: "grenouilleapi_bot"
    build:
      context: ..
      dockerfile: docker/grenouilleapi/Dockerfile
    entrypoint: python3 /grenouille/backend/bot_app.py
    depends_on:
      - grenouilleapi_postgres
