"""1/ Initial database.

Revision ID: 8f07736702ab
Revises: None
Create Date: 2017-05-09 15:27:15.700038

"""

# revision identifiers, used by Alembic.
revision = '8f07736702ab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
