"""2/ Add CSV database.

Revision ID: 0d4fdbeccbf8
Revises: 0f2a9a4f78e9
Create Date: 2018-07-24 03:55:17.601371

"""

# revision identifiers, used by Alembic.
revision = '0d4fdbeccbf8'
down_revision = '0f2a9a4f78e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_data',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csv_data')
    # ### end Alembic commands ###
