"""1/ 1.2.0 database

Revision ID: 0f2a9a4f78e9
Revises: None
Create Date: 2018-07-13 16:25:53.911926

"""

# revision identifiers, used by Alembic.
revision = '0f2a9a4f78e9'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ScalarListType


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_scope',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'channel', 'scope')
    )
    op.create_table('api_key',
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_table('api_key_scope',
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['key_hash'], ['api_key.key_hash'], ),
    sa.PrimaryKeyConstraint('key_hash', 'channel', 'scope')
    )

    op.create_table('stream',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('google_calendar_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_configuration',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('csv_data',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )

    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('team1', sa.Integer(), nullable=False),
    sa.Column('team2', sa.Integer(), nullable=False),
    sa.Column('team1_ids', ScalarListType(), nullable=False),
    sa.Column('team2_ids', ScalarListType(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_FOR_BOT', 'CREATION_IN_PROGRESS', 'WAITING_FOR_PLAYERS', 'GAME_IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='gamestatus'), nullable=False),
    sa.Column('team_choosing_first', sa.Integer(), nullable=False),
    sa.Column('bot', sa.String(), nullable=True),
    sa.Column('valve_id', sa.BigInteger(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_vip',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('CASTER', 'ADMIN', name='gameviptype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('dota_heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('localized_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dota_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('localized_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dota_pro_players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('team', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dota_pro_teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('api_key')

    op.drop_table('stream')
    op.drop_table('dynamic_configuration')
    op.drop_table('csv_data')

    op.drop_table('game')
    op.drop_table('game_vip')

    op.drop_table('dota_heroes')
    op.drop_table('dota_items')
    op.drop_table('dota_pro_players')
    op.drop_table('dota_pro_teams')
    # ### end Alembic commands ###
