"""4/ Add a pro player table

Revision ID: 3538867d1f20
Revises: 199b7870ef3c
Create Date: 2018-08-11 22:29:28.096222

"""

# revision identifiers, used by Alembic.
revision = '3538867d1f20'
down_revision = '199b7870ef3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dota_pro_players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('team', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dota_pro_players')
    # ### end Alembic commands ###
