"""3/ Add avatar and nickname to a specific user.

Revision ID: 401a4f11af01
Revises: e61b6a6a2b8a
Create Date: 2017-09-12 03:54:01.268268

"""

# revision identifiers, used by Alembic.
revision = '401a4f11af01'
down_revision = 'e61b6a6a2b8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avatar_full', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avatar_medium', sa.String(), nullable=True))
    op.add_column('user', sa.Column('nickname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'avatar_medium')
    op.drop_column('user', 'avatar_full')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
