"""5/ Create user table

Revision ID: 4f76daf07dd3
Revises: f574e4c54d99
Create Date: 2018-06-20 20:49:16.505054

"""

# revision identifiers, used by Alembic.
revision = '4f76daf07dd3'
down_revision = 'f574e4c54d99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
