"""5/ Add pro teams table

Revision ID: 617868c21f72
Revises: 3538867d1f20
Create Date: 2018-08-12 19:36:15.915749

"""

# revision identifiers, used by Alembic.
revision = '617868c21f72'
down_revision = '3538867d1f20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dota_pro_teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dota_pro_teams')
    # ### end Alembic commands ###
