"""3/ Add game vips.

Revision ID: 6820c4546515
Revises: c3369e72755b
Create Date: 2018-01-22 04:10:59.017125

"""

# revision identifiers, used by Alembic.
revision = '6820c4546515'
down_revision = 'c3369e72755b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_vip',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('CASTER', 'ADMIN', name='gameviptype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_vip')
    # ### end Alembic commands ###
