"""1/ First clean database

Revision ID: b0b1f904d165
Revises: None
Create Date: 2018-01-25 02:48:41.036520

"""

# revision identifiers, used by Alembic.
revision = 'b0b1f904d165'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ScalarListType


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('team1', sa.Integer(), nullable=False),
    sa.Column('team2', sa.Integer(), nullable=False),
    sa.Column('team1_ids', ScalarListType(), nullable=False),
    sa.Column('team2_ids', ScalarListType(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_FOR_BOT', 'CREATION_IN_PROGRESS', 'WAITING_FOR_PLAYERS', 'GAME_IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='gamestatus'), nullable=False),
    sa.Column('team_choosing_first', sa.Integer(), nullable=False),
    sa.Column('valve_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_vip',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('CASTER', 'ADMIN', name='gameviptype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('nickname_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_refresh_token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'refresh_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_refresh_token')
    op.drop_table('user')
    op.drop_table('game_vip')
    op.drop_table('game')
    # ### end Alembic commands ###
