"""2/ First game version

Revision ID: c3369e72755b
Revises: d8c97ac97e6c
Create Date: 2018-01-22 03:34:46.885948

"""

# revision identifiers, used by Alembic.
revision = 'c3369e72755b'
down_revision = 'd8c97ac97e6c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ScalarListType


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('team1', sa.String(), nullable=False),
    sa.Column('team2', sa.String(), nullable=False),
    sa.Column('team1_ids', ScalarListType(), nullable=False),
    sa.Column('team2_ids', ScalarListType(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_FOR_OTHER_GAME', 'WAITING_FOR_BOT', 'CREATION_IN_PROGRESS', 'WAITING_FOR_PLAYERS', 'GAME_IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='gamestatus'), nullable=False),
    sa.Column('waited_game', sa.BigInteger(), nullable=True),
    sa.Column('valve_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
