"""2/ Add table to manage refresh tokens.

Revision ID: e61b6a6a2b8a
Revises: 8f07736702ab
Create Date: 2017-09-11 18:38:52.544771

"""

# revision identifiers, used by Alembic.
revision = 'e61b6a6a2b8a'
down_revision = '8f07736702ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'refresh_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_refresh_token')
    # ### end Alembic commands ###
