"""4/ Add dynamic configuration

Revision ID: f574e4c54d99
Revises: 64a92297f9a4
Create Date: 2018-03-01 15:23:43.215052

"""

# revision identifiers, used by Alembic.
revision = 'f574e4c54d99'
down_revision = '64a92297f9a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_configuration',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dynamic_configuration')
    # ### end Alembic commands ###
